### PR TITLE
feat(environment): create the EZE environment for spec tests

### PR DESCRIPTION
**Pull request by aivinog1**
This is the first part of #100.

I just create the EZE environment which consists of EZE as Zeebe part and ZeeQS in the Docker as query service. We could improve it in the future but this is for start.

### CODE REVIEW

**Comment by saig0** [comment]
@aivinog1 thank you for your contribution. :tada: 

Currently, I'm busy and don't have time to review your changes (we are short before the Zeebe release). I'll have a look at least in two weeks. :eyes:

**Comment by aivinog1** [comment]
> Currently, I'm busy and don't have time to review your changes (we are short before the Zeebe release). I'll have a look at least in two weeks. 👀

Sure, no problem :) If you need some help, you can ask me :)

**Review by saig0 — CHANGES_REQUESTED** [review]
@aivinog1 great contribution. :tada: In general, I like the changes. :+1: 

One minor comment: the `ZeebeTestRunnerTest` is taking too long (7 minutes on my laptop). The parameterized tests are a good idea but the execution is too long. I would be find with a smaller subset of tests to verify the correctness. 

One major comment: I'm not sure about the splitting of the environment. It's working but it feels not the right abstraction. I think that a new test runner for EZE would be a better option with more flexibility. We could extract the common parts (ZeeQS client) into separate modules.

Do you agree? Do you want to make the change?

If not, it's completely fine. I would accept the PR and do the other change by myself.

**Comment by aivinog1** [comment]
Hey @saig0! Sure, I will try to fix it :)

**Comment by aivinog1** [comment]
Hey @saig0! Can you check this out, please? :)

**Comment by aivinog1** [comment]
@saig0 Hey! Can you take a look at this, please? :)

**Comment by saig0** [comment]
@aivinog1 yes! I'm sorry but the delay. :bow: 
We got a lot of great contributions during Hacktoberfest. I'm still in the process of reviewing them. :sweat_smile: I'll have a look at your PR as soon as possible.

**Comment by saig0** [comment]
@aivinog1 I'm sorry about the delay. :bow: I'll look into your PR next week.

**Review by saig0 — COMMENTED** [review]
@aivinog1 I had a look at your changes. Thank you for all your effort. :cake: :+1:  

I'm still struggling a bit with the structure. To get a better idea, of what I would like to have I'll code a bit myself over the holidays. I will probably use some of your code. 

I'll keep you updated.

**Comment by saig0** [comment]
I'm closing this PR in favor of #212. 

The PR #212 adds a new test runner for EZE next to the existing test runner for Zeebe. Instead of ZeeQS, the test runner uses the records directly from EZE to collect the state of the process instances. Using only EZE reduces the startup time to less than a second. :rocket:   

@aivinog1 thank you for your contribution and for sharing your ideas. :bow:

**Pull request closed without merging**
